version: '3.8'
services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
  
  pgadmin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-network
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
networks:
  postgres-network:
    driver: bridge