version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysqldb-data:/var/lib/mysql
    networks:
      - mysqldb-network
    

volumes:
  mysqldb-data:
    name: mysqldb-data
networks:
  mysqldb-network:
    name: mysqldb-network